name: CI

on:
  push:
    branches:
      #- master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl-version: ['5.24']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: local
          key: local-${{ runner.os }}-${{ matrix.perl-version }}-${{ hashFiles('cpanfile') }}
          restore-keys: |
            local-${{ runner.os }}-${{ matrix.perl-version }}-

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - run: cpanm -L local --installdeps --notest .

      - run: prove -Ilocal/lib/perl5 -Ilib -lv t
